using System.Security.Cryptography;
using Bunq.Sdk.Model.Core;
using Bunq.Sdk.Security;

namespace Bunq.Sdk.Context
{
    /// <summary>
    /// Context of the bunq API installation.
    /// </summary>
    public class InstallationContext
    {
        public string Token { get; private set; }
        public RSA KeyPairClient { get; private set; }
        public RSA PublicKeyServer { get; private set; }

        internal InstallationContext(Installation installation, RSA keyPairClient) :
            this(installation.SessionToken.Token, keyPairClient,
                SecurityUtils.CreatePublicKeyFromPublicKeyFormattedString(installation.GetPublicKeyServerString()))
        {
        }

        /// <param name="token">Installation token returned as a response to the POST /installation</param>
        /// <param name="keyPairClient">Client key pair generated by SDK (Private + Public)</param>
        /// <param name="publicKeyServer">Server public key returned as a response to the POST /installation</param>
        public InstallationContext(string token, RSA keyPairClient, RSA publicKeyServer)
        {
            Token = token;
            KeyPairClient = keyPairClient;
            PublicKeyServer = publicKeyServer;
        }
    }
}
